# Generated by Django 5.1.6 on 2025-02-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('DNI', models.IntegerField()),
                ('age', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('parents', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('complaintType', models.CharField(max_length=100)),
                ('complaintDetail', models.TextField()),
            ],
        ),
    ]
