# Generated by Django 5.1.6 on 2025-02-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='type',
            new_name='service',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='DNI',
            field=models.CharField(max_length=200),
        ),
    ]
